.TH SPG 1 LOCAL
.SH NAME
spg - Static Page Generator
.SH DESCRIPTION
Form more details go to README.md
.SH SYNOPSIS
.B spg
[--config=PATH]
.SH OPTIONS
.TP
.B --config
Path to config (ini file), default is ./config.ini
.SH EXAMPLE
spg --config=./config.ini
.SH AUTHOR 
Kamil Harasimowicz